name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper versioning
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -e .
    
    - name: Build documentation
      run: |
        cd docs
        make clean
        make html
    
    - name: Check documentation build
      run: |
        cd docs/_build/html
        python -c "
        import os
        files = os.listdir('.')
        print('Built files:', files)
        assert 'index.html' in files, 'index.html not found'
        assert 'api.html' in files, 'api.html not found'
        assert 'strategies.html' in files, 'strategies.html not found'
        print('Documentation build successful!')
        "
    
    - name: Debug artifact path
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      run: |
        echo "Current branch: ${{ github.ref }}"
        echo "Event name: ${{ github.event_name }}"
        echo "Artifact path contents:"
        ls -la ./docs/_build/html/
        echo "Checking if index.html exists:"
        test -f ./docs/_build/html/index.html && echo "✅ index.html exists" || echo "❌ index.html missing"
    
    - name: Upload documentation artifact
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./docs/_build/html
        retention-days: 1
    
    - name: Deploy to GitHub Pages
      id: deployment
      if: github.ref == 'refs/heads/main' || github.event_name == 'release'
      uses: actions/deploy-pages@v4
